### ISSUE TITLE
代理没效果.

### ISSUE THREAD

**Issue by larry-ct** [Poseidon-Service-Framework/poseidon-chrome-proxy#2]
![image](https://user-images.githubusercontent.com/40970099/137678782-ac83828f-9756-4f3a-9960-d6cd436b57b2.png)
随便 配置的都不行 不会走代理 ..本地是有vpn 不过我都退出了 还是不行 系统WIN11

**Comment by muggle0** [comment]
1. 浏览器缓存导致无法代理，暂时的解决办法：
https://blog.csdn.net/weixin_46544385/article/details/110094588

2. 代理的ip:端口网络不通导致代理失效，解决办法：
确保ip:端口能访问后重新关闭然后开启代理
