### ISSUE TITLE
根据ip好像不能代理啊，我试了多次报错

### ISSUE THREAD

**Issue by zundaren** [Poseidon-Service-Framework/poseidon-chrome-proxy#4]
![image](https://user-images.githubusercontent.com/44863479/137695144-b52eda3d-ea40-48ec-953f-680bfc432bb4.png)

**Comment by muggle0** [comment]
![image](https://user-images.githubusercontent.com/37202701/138025934-62805a25-b343-4952-ae75-2ae4adae2d67.png)
你好是可以代理的，先启动你本地项目，然后再重新加载扩展程序尝试一下
