### ISSUE TITLE
代理未生效情况收集issue

### ISSUE THREAD

**Issue by muggle0** [Poseidon-Service-Framework/poseidon-chrome-proxy#5]
目前有许多小伙伴用这个插件后，代理并未生效；针对这些情况，麻烦大家在下方评论json配置以及谷歌浏览器的版本号

**Comment by zundaren** [comment]
<html>
<body>


Google Chrome | 94.0.4606.61 (正式版本) （64 位）
-- | --
修订版本 | 418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}
操作系统 | Windows 10 Version 21H1 (Build 19043.1237)
JavaScript | V8 9.4.146.16


</body>
</html>

**Comment by zundaren** [comment]
总是报什么跨域，项目人家前端开发的都能调

**Comment by kulalasmile** [comment]
Json配置：
`[
  {
    "domain": "172.31.123.xx:3101",
    "matchingRules": [
      {
        "route": "/api/xx/xx/oauth/token",
        "targetUrl": "localhost:20003/xx/xx/oauth/token"
      }
    ]
  }
]`


浏览器版本：
95.0.4638.69（正式版本） （64 位）

**Comment by ym520** [comment]
<html>
<body>


Microsoft Edge | 100.0.1185.50 (正式版本) （64 位）
-- | --
操作系统 | Windows 10 Version 20H2(Build 19042.985)


</body>
</html>
